Module Output_Mod
    
    use Problem_Mod
    use Geometry_Mod
    !!Handles the data generated by solver routines, generating data readable by paraview etc
    !!Any other postprocessing of data would also go here

    Implicit None
    public :: GenerateVTU
contains

Subroutine GenerateVTU(Problem,Geometry,Flux)
    type(t_problem) :: Problem
    type(t_Geometry) :: Geometry
    Integer :: ii, jj, N_Cells, N_Nodes, N_Regions, Ref_x, Ref_y
    Integer :: Cell_x, Cell_y, CellID
    Integer, allocatable, dimension(:) :: RegionNodes
    Integer, parameter :: vtufile = 202 
    Real(kind=dp) :: CentralPos(2), dx, dy, Pos(3)
    Real(kind=dp), allocatable, dimension(:) :: Flux, Boundary_Pos
    !!Generate the VTU file using the resultand flux sorted in the PETSc vector x

    !!Extract relevant problem and geometry information
    N_Cells = Get_N_FiniteVolumes(Geometry)
    N_Regions = Get_N_Regions(Problem)
    Ref_x = Get_Refinement_x(Problem)
    Ref_y = Get_Refinement_y(Problem)

    !! Number of nodes in problem for paraview to visualise
    N_Nodes = N_Cells*4

    ! print *, 'N_Cells:', N_Cells
    ! print *, 'N_Regions:', N_Regions    
    ! print *, 'Ref_x:', Ref_x 
    ! print *, 'Ref_y:', Ref_y
    ! print *, 'N_Nodes:', N_Nodes
    

    !!Generate VTU file
    Open(vtufile,File='OutputFile.vtu',Status='Replace')

    !!Describe the format
    Write(vtufile,'(g0)') "<?xml version=""1.0""?>"
    Write(vtufile,'(g0)') "<VTKFile type=""UnstructuredGrid"" version=""0.1"" byte_order=""LittleEndian"">"
    Write(vtufile,'(g0)',advance='no') "  "
    Write(vtufile,'(g0)') "<UnstructuredGrid>"

    !!Describe the amount of data
    Write(vtufile,'(g0)',advance='no') "    "
    Write(vtufile,'(g0)',advance='no') '<Piece NumberOfPoints="'
    Write(vtufile,'(g0)',advance='no') N_Nodes
    Write(vtufile,'(g0)',advance='no') '" NumberOfCells="'
    Write(vtufile,'(g0)',advance='no') N_Cells
    Write(vtufile,'(g0)') '">'

    !!Cell data section 
    Write(vtufile,'(g0)',advance='no') "      "
    Write(vtufile,'(g0)') '<CellData Scalars="Region, Cell ID, Scalar Flux">'

    Write(vtufile,'(g0)',advance='no') "        "
    Write(vtufile,'(g0)') '<DataArray Name="Region" format="ascii" type="Int32" >'
    Write(vtufile,'(g0)',advance='no') "          "

    !!Loop over the problem to find the region number
    Do ii = 1, N_Regions
        Do jj = 1, Ref_x*Ref_y
            Write(vtufile,'(g0)',advance='no') ii
            Write(vtufile,'(g0)',advance='no') " "
        EndDo    
    EndDo
    Write(vtufile,'(g0)') ""
    Write(vtufile,'(g0)',advance='no') "        "
    Write(vtufile,'(g0)') "</DataArray>"

    Write(vtufile,'(g0)',advance='no') "        "
    Write(vtufile,'(g0)') '<DataArray Name="Cell ID" format="ascii" type="Int32" >'
    Write(vtufile,'(g0)',advance='no') "          "

    Do ii = 1, N_Cells
        Write(vtufile,'(g0)',advance='no') ii
        Write(vtufile,'(g0)',advance='no') " "
    EndDo
    Write(vtufile,'(g0)') ""
    Write(vtufile,'(g0)',advance='no') "        "
    Write(vtufile,'(g0)') "</DataArray>"

    Write(vtufile,'(g0)',advance='no') "        "
    Write(vtufile,'(g0)') '<DataArray Name="Scalar Flux" format="ascii" type="Float64" >'
    Write(vtufile,'(g0)',advance='no') "          "

    Do ii = 1, N_Cells
        Write(vtufile,'(E14.6)',advance='no') Flux(ii)
        Write(vtufile,'(g0)',advance='no') " "
    EndDo
    Write(vtufile,'(g0)') ""
    Write(vtufile,'(g0)',advance='no') "        "
    Write(vtufile,'(g0)') "</DataArray>"
    

    Write(vtufile,'(g0)',advance='no') "      "
    Write(vtufile,'(g0)') "</CellData>"


    !!Fill in the point data
    Write(vtufile,'(g0)',advance='no') "      "
    Write(vtufile,'(g0)') "<Points>"
    Write(vtufile,'(g0)',advance='no') "        "
    Write(vtufile,'(g0)') "<DataArray Name=""Coordinates"" NumberOfComponents=""3"" format=""ascii"" type=""Float64"" >"
    Write(vtufile,'(g0)',advance='no') "          "

    !! Loop over the cells
    CellID = 0 
    Pos = 0._dp
    Do ii = 1, N_Regions
        Do Cell_y = 1, Ref_y 
            Do Cell_x = 1, Ref_x
                !! Update ID of cell
                CellID = CellID + 1
                !! Get centre, dx and dy for cell
                CentralPos = Get_FV_CentralPos(Geometry,CellID)
                dx = Get_FV_dx(Geometry,CellID)
                dy = Get_FV_dy(Geometry,CellID)
                !! Bottom-Left Node
                Pos(:2) = CentralPos(:) + 0.5_dp*[-dx,-dy]
                Write(vtufile,'(3E14.6)',advance='no') Pos
                !! Bottom-Right Node
                Pos(:2) = CentralPos(:) + 0.5_dp*[dx,-dy]
                Write(vtufile,'(3E14.6)',advance='no') Pos
                !! Top-Right Node
                Pos(:2) = CentralPos(:) + 0.5_dp*[dx,dy]
                Write(vtufile,'(3E14.6)',advance='no') Pos
                !! Top-Left Node
                Pos(:2) = CentralPos(:) + 0.5_dp*[-dx,dy]
                Write(vtufile,'(3E14.6)',advance='no') Pos
            End Do 
        End Do 
    End Do 
    Write(vtufile,'(g0)') ""
    Write(vtufile,'(g0)',advance='no') "        "
    Write(vtufile,'(g0)') "</DataArray>"
    Write(vtufile,'(g0)',advance='no') "      "
    Write(vtufile,'(g0)') "</Points>"


    !!Fill in the cell data
    Write(vtufile,'(g0)',advance='no') "      "
    Write(vtufile,'(g0)') "<Cells>"
    !!Connectivity
    Write(vtufile,'(g0)',advance='no') "        "
    Write(vtufile,'(g0)') '<DataArray type="Int32" Name="connectivity" format="ascii">'
    Write(vtufile,'(g0)',advance='no') "          "
    Do ii = 1, N_Nodes
        Write(vtufile,'(g0)',advance='no') ii-1
        Write(vtufile,'(g0)',advance='no') " "
    EndDo
    Write(vtufile,'(g0)') ""
    Write(vtufile,'(g0)',advance='no') "        "
    Write(vtufile,'(g0)') " </DataArray>"
    !!Offsets
    Write(vtufile,'(g0)',advance='no') "        "
    Write(vtufile,'(g0)') '<DataArray type="Int32" Name="offsets" format="ascii">'
    Write(vtufile,'(g0)',advance='no') "          "
    Do ii = 1, N_Cells
        Write(vtufile,'(g0)',advance='no') ii*4
        Write(vtufile,'(g0)',advance='no') " "
    EndDo
    Write(vtufile,'(g0)') ""
    Write(vtufile,'(g0)',advance='no') "        "
    Write(vtufile,'(g0)') " </DataArray>"
    ! !!Types
    Write(vtufile,'(g0)',advance='no') "        "
    Write(vtufile,'(g0)',advance='no') "  "
    Write(vtufile,'(g0)') '<DataArray type="Int32" Name="types" format="ascii">'
    Write(vtufile,'(g0)',advance='no') "          "
    Do ii = 1, N_Cells
        Write(vtufile,'(g0)',advance='no') 5
        Write(vtufile,'(g0)',advance='no') " "
    EndDo
    Write(vtufile,'(g0)') ""
    Write(vtufile,'(g0)',advance='no') "        "
    Write(vtufile,'(g0)') " </DataArray>"

    Write(vtufile,'(g0)',advance='no') "      "
    Write(vtufile,'(g0)') "</Cells>"
    Write(vtufile,'(g0)',advance='no') "    "
    Write(vtufile,'(g0)') '</Piece>'
    Write(vtufile,'(g0)',advance='no') "  "
    Write(vtufile,'(g0)') "</UnstructuredGrid>"
    Write(vtufile,'(g0)') "</VTKFile>"

    Close(vtufile)
End Subroutine GenerateVTU

End Module
